export const SOURCES = [
  
    { name: "TechCrunch", url: "https://techcrunch.com" },
    { name: "The Verge", url: "https://www.theverge.com" },
    { name: "Bloomberg Tech", url: "https://www.bloomberg.com/technology" },
  
    // --- Big Tech & Major News ---
    { name: "Wired", url: "https://www.wired.com" },
    { name: "Ars Technica", url: "https://arstechnica.com" },
    { name: "The Information", url: "https://www.theinformation.com" },
    { name: "Axios Tech", url: "https://www.axios.com/tech" },
    { name: "Recode", url: "https://www.vox.com/recode" },
    { name: "Financial Times Tech", url: "https://www.ft.com/technology" },
    { name: "New York Times Technology", url: "https://www.nytimes.com/section/technology" },
    { name: "Washington Post Tech", url: "https://www.washingtonpost.com/technology" },
    { name: "Reuters Tech", url: "https://www.reuters.com/technology" },
    { name: "BBC Technology", url: "https://www.bbc.com/news/technology" },
    { name: "CNN Tech", url: "https://www.cnn.com/business/tech" },
    { name: "CNBC Tech", url: "https://www.cnbc.com/technology" },
    { name: "NBC News Tech", url: "https://www.nbcnews.com/tech" },
    { name: "MarketWatch Tech", url: "https://www.marketwatch.com/technology" },
    { name: "Forbes Tech", url: "https://www.forbes.com/tech" },
    { name: "Fortune Tech", url: "https://fortune.com/tech" },
    { name: "Bloomberg AI", url: "https://www.bloomberg.com/topics/artificial-intelligence" },
  
    // --- AI & ML News ---
    { name: "VentureBeat AI", url: "https://venturebeat.com/category/ai" },
    { name: "MIT Technology Review AI", url: "https://www.technologyreview.com/ai" },
    { name: "AI Weekly", url: "https://aiweekly.co" },
    { name: "Import AI", url: "https://jack-clark.net" },
    { name: "DeepMind Blog", url: "https://deepmind.google/discover/blog" },
    { name: "OpenAI Blog", url: "https://openai.com/blog" },
    { name: "Anthropic Blog", url: "https://www.anthropic.com/index" },
    { name: "Google AI Blog", url: "https://ai.googleblog.com" },
    { name: "Meta AI Blog", url: "https://ai.meta.com/blog" },
    { name: "NVIDIA Blog", url: "https://blogs.nvidia.com" },
    { name: "HuggingFace Blog", url: "https://huggingface.co/blog" },
    { name: "Stability AI Blog", url: "https://stability.ai/blog" },
  
    // --- Cybersecurity ---
    { name: "Bleeping Computer", url: "https://www.bleepingcomputer.com" },
    { name: "Krebs on Security", url: "https://krebsonsecurity.com" },
    { name: "Dark Reading", url: "https://www.darkreading.com" },
    { name: "The Hacker News", url: "https://thehackernews.com" },
    { name: "Security Week", url: "https://www.securityweek.com" },
    { name: "Schneier on Security", url: "https://www.schneier.com" },
  
    // --- Developer / Engineering ---
    { name: "Stack Overflow Blog", url: "https://stackoverflow.blog" },
    { name: "GitHub Blog", url: "https://github.blog" },
    { name: "Hacker News", url: "https://news.ycombinator.com" },
    { name: "Dev.to", url: "https://dev.to" },
    { name: "Hashnode", url: "https://hashnode.com" },
    { name: "Reddit r/technology", url: "https://www.reddit.com/r/technology" },
    { name: "Reddit r/MachineLearning", url: "https://www.reddit.com/r/MachineLearning" },
    { name: "Reddit r/artificial", url: "https://www.reddit.com/r/artificial" },
    { name: "Smashing Magazine", url: "https://www.smashingmagazine.com" },
    { name: "CSS-Tricks", url: "https://css-tricks.com" },
    { name: "A List Apart", url: "https://alistapart.com" },
  
    // --- Business, Startups & VC ---
    { name: "Crunchbase News", url: "https://news.crunchbase.com" },
    { name: "Pitchbook News", url: "https://pitchbook.com/news" },
    { name: "SaaStr", url: "https://www.saastr.com" },
    { name: "Product Hunt", url: "https://www.producthunt.com" },
    { name: "IndieHackers", url: "https://www.indiehackers.com" },
    { name: "Andreessen Horowitz (a16z)", url: "https://a16z.com" },
    { name: "Y Combinator Blog", url: "https://www.ycombinator.com/blog" },
    { name: "Sequoia Capital Articles", url: "https://www.sequoiacap.com/articles" },
    { name: "Greylock Insights", url: "https://greylock.com/insights" },
    { name: "Lightspeed Venture Partners", url: "https://lightspeedvp.com/insights" },
  
    // --- Hardware / Chips ---
    { name: "Tom’s Hardware", url: "https://www.tomshardware.com" },
    { name: "AnandTech", url: "https://www.anandtech.com" },
    { name: "NotebookCheck", url: "https://www.notebookcheck.net" },
    { name: "Digital Trends", url: "https://www.digitaltrends.com" },
    { name: "Slashdot", url: "https://slashdot.org" },
    { name: "PCMag", url: "https://www.pcmag.com" },
  
    // --- Mobile / Consumer Tech ---
    { name: "Android Authority", url: "https://www.androidauthority.com" },
    { name: "9to5Mac", url: "https://9to5mac.com" },
    { name: "9to5Google", url: "https://9to5google.com" },
    { name: "MacRumors", url: "https://www.macrumors.com" },
    { name: "Gizmodo", url: "https://gizmodo.com" },
    { name: "Engadget", url: "https://www.engadget.com" },
    { name: "CNET", url: "https://www.cnet.com" },
    { name: "XDA Developers", url: "https://www.xda-developers.com" },
  
    // --- Data, Cloud & Enterprise ---
    { name: "InfoQ", url: "https://infoq.com" },
    { name: "TechRepublic", url: "https://www.techrepublic.com" },
    { name: "Protocol", url: "https://www.protocol.com" },
    { name: "SDxCentral", url: "https://www.sdxcentral.com" },
    { name: "Diginomica", url: "https://diginomica.com" },
    { name: "SiliconANGLE", url: "https://siliconangle.com" },
    { name: "The Register", url: "https://www.theregister.com" },
  
    // --- Gaming & Interactive Media ---
    { name: "IGN", url: "https://www.ign.com" },
    { name: "Kotaku", url: "https://kotaku.com" },
    { name: "Polygon", url: "https://www.polygon.com" },
    { name: "GameSpot", url: "https://www.gamespot.com" },
    { name: "Eurogamer", url: "https://www.eurogamer.net" },
  
    // --- Robotics & Future Tech ---
    { name: "IEEE Spectrum", url: "https://spectrum.ieee.org" },
    { name: "NextBigFuture", url: "https://www.nextbigfuture.com" },
    { name: "Futurism", url: "https://futurism.com" },
    { name: "Singularity Hub", url: "https://singularityhub.com" },
  
    // --- Global Tech News ---
    { name: "Tech.eu", url: "https://tech.eu" },
    { name: "Sifted", url: "https://sifted.eu" },
    { name: "The Hacker News India", url: "https://newsable.asianetnews.com/technology" },
    { name: "Nikkei Asia Tech", url: "https://asia.nikkei.com/Business/Tech" },
    { name: "South China Morning Post Tech", url: "https://www.scmp.com/tech" },
    { name: "ET Tech (India)", url: "https://tech.economictimes.indiatimes.com" },
    { name: "LiveMint Tech", url: "https://www.livemint.com/technology" },
    { name: "GadgetFlow", url: "https://thegadgetflow.com" },
    { name: "T3", url: "https://www.t3.com" },
    { name: "TechSpot", url: "https://www.techspot.com" },
    { name: "MakeUseOf", url: "https://www.makeuseof.com" },
    { name: "How-To Geek", url: "https://www.howtogeek.com" },
    { name: "Lifehacker", url: "https://lifehacker.com" },
    { name: "ReadWrite", url: "https://readwrite.com" },
    { name: "ZDNet", url: "https://www.zdnet.com" },
    { name: "Gigaom", url: "https://gigaom.com" },
    { name: "BetaNews", url: "https://betanews.com" },
  
    // --- AI / Research Labs & Orgs ---
    { name: "Allen Institute for AI (AI2)", url: "https://allenai.org" },
    { name: "ML Collective", url: "https://mlcollective.org" },
    { name: "EleutherAI", url: "https://www.eleuther.ai" },
    { name: "MosaicML Blog", url: "https://www.mosaicml.com/blog" },
    { name: "Cohere Blog", url: "https://txt.cohere.com" },
    { name: "Perplexity Blog", url: "https://blog.perplexity.ai" },
    { name: "Lambda Labs Blog", url: "https://blog.lambdalabs.com" },
    { name: "OpenMMLab", url: "https://openmmlab.com" },
    { name: "Berkeley AI Research", url: "https://bair.berkeley.edu/blog" },
    { name: "Stanford HAI", url: "https://hai.stanford.edu/news" },
  
    // --- Cloud / SaaS ---
    { name: "AWS News Blog", url: "https://aws.amazon.com/blogs/aws" },
    { name: "Google Cloud Blog", url: "https://cloud.google.com/blog" },
    { name: "Microsoft Azure Blog", url: "https://azure.microsoft.com/en-us/blog" },
    { name: "Oracle Cloud Blog", url: "https://blogs.oracle.com/cloud" },
    { name: "Cloudflare Blog", url: "https://blog.cloudflare.com" },
    { name: "DigitalOcean Blog", url: "https://www.digitalocean.com/blog" },
    { name: "Snowflake Blog", url: "https://www.snowflake.com/blog" },
    { name: "Databricks Blog", url: "https://www.databricks.com/blog" },
    { name: "MongoDB Blog", url: "https://www.mongodb.com/blog" },
    { name: "Elastic Blog", url: "https://www.elastic.co/blog" },
  
    // --- DevOps / Infra ---
    { name: "Kubernetes Blog", url: "https://kubernetes.io/blog" },
    { name: "Docker Blog", url: "https://www.docker.com/blog" },
    { name: "HashiCorp Blog", url: "https://www.hashicorp.com/blog" },
    { name: "Terraform Registry Blog", url: "https://registry.terraform.io" },
    { name: "CircleCI Blog", url: "https://circleci.com/blog" },
    { name: "GitLab Blog", url: "https://about.gitlab.com/blog" },
    { name: "Jenkins Blog", url: "https://www.jenkins.io/blog" },
    { name: "Ansible Blog", url: "https://www.ansible.com/blog" },
    { name: "Prometheus Blog", url: "https://prometheus.io/blog" },
    { name: "Grafana Blog", url: "https://grafana.com/blog" },
  
    // --- Big Data / Analytics ---
    { name: "KDNuggets", url: "https://www.kdnuggets.com" },
    { name: "Towards Data Science", url: "https://towardsdatascience.com" },
    { name: "DataCamp Blog", url: "https://www.datacamp.com/blog" },
    { name: "Analytics India Magazine", url: "https://analyticsindiamag.com" },
    { name: "Data Engineering Weekly", url: "https://www.dataengineeringweekly.com" },
    { name: "Substack: Chip Huyen", url: "https://chiphuyen.substack.com" },
    { name: "Substack: LLM Report", url: "https://llmreport.substack.com" },
    { name: "Substack: AI Tinkerers", url: "https://aitinkerers.org" },
    { name: "Substack: Benedict Evans", url: "https://www.ben-evans.com" },
    { name: "Substack: Stratechery", url: "https://stratechery.com" },
  
    // --- More Tech / News Sites ---
    { name: "TechNode", url: "https://technode.com" },
    { name: "Tech in Asia", url: "https://www.techinasia.com" },
    { name: "VentureBeat", url: "https://venturebeat.com" },
    { name: "TechSpot News", url: "https://www.techspot.com/news" },
    { name: "Digital Journal", url: "https://www.digitaljournal.com" },
    { name: "TNW (The Next Web)", url: "https://thenextweb.com" },
    { name: "Computerworld", url: "https://www.computerworld.com" },
    { name: "Network World", url: "https://www.networkworld.com" },
    { name: "InfoWorld", url: "https://www.infoworld.com" },
    { name: "MacWorld", url: "https://www.macworld.com" },
  
    // --- Automotive / EV / Mobility ---
    { name: "Electrek", url: "https://electrek.co" },
    { name: "InsideEVs", url: "https://insideevs.com" },
    { name: "Teslarati", url: "https://www.teslarati.com" },
    { name: "MotorTrend", url: "https://www.motortrend.com" },
    { name: "Car and Driver", url: "https://www.caranddriver.com" },
    { name: "The Drive", url: "https://www.thedrive.com" },
    { name: "Road & Track", url: "https://www.roadandtrack.com" },
    { name: "Jalopnik", url: "https://jalopnik.com" },
    { name: "AutoBlog", url: "https://www.autoblog.com" },
    { name: "Top Gear", url: "https://www.topgear.com" },
  
    // --- Enterprise / CIO-level ---
    { name: "CIO.com", url: "https://www.cio.com" },
    { name: "CIO Dive", url: "https://www.ciodive.com" },
    { name: "CFO Dive", url: "https://www.cfodive.com" },
    { name: "TechTarget", url: "https://www.techtarget.com" },
    { name: "SD Times", url: "https://sdtimes.com" },
    { name: "EnterpriseAI", url: "https://www.enterpriseai.news" },
    { name: "Data Center Knowledge", url: "https://www.datacenterknowledge.com" },
    { name: "The New Stack", url: "https://thenewstack.io" },
    { name: "Silicon Republic", url: "https://www.siliconrepublic.com" },
    { name: "ITPro", url: "https://www.itpro.com" },
  
    // --- Robotics / Automation / Space ---
    { name: "Robotics 24/7", url: "https://www.robotics247.com" },
    { name: "Robot Report", url: "https://www.therobotreport.com" },
    { name: "NASA News", url: "https://www.nasa.gov/news" },
    { name: "Space.com", url: "https://www.space.com" },
    { name: "SpaceNews", url: "https://spacenews.com" },
    { name: "Ars Technica Space", url: "https://arstechnica.com/space" },
    { name: "Tesmanian Space", url: "https://www.tesmanian.com/blogs/tesmanian-blog/tagged/space" },
    { name: "SpaceX Updates", url: "https://www.spacex.com/news" },
    { name: "Blue Origin Blog", url: "https://www.blueorigin.com/news" },
    { name: "European Space Agency", url: "https://www.esa.int/News" },
  
    // --- Finance / Markets / Crypto-Tech ---
    { name: "Yahoo Finance Tech", url: "https://finance.yahoo.com/tech" },
    { name: "CoinDesk", url: "https://www.coindesk.com" },
    { name: "CoinTelegraph", url: "https://cointelegraph.com" },
    { name: "Decrypt", url: "https://decrypt.co" },
    { name: "Blockworks", url: "https://blockworks.co" },
    { name: "The Defiant", url: "https://thedefiant.io" },
    { name: "Bankless", url: "https://bankless.com" },
    { name: "Messari", url: "https://messari.io" },
    { name: "CryptoSlate", url: "https://cryptoslate.com" },
    { name: "Bitcoin Magazine", url: "https://bitcoinmagazine.com" },
  
    // --- Design / Product ---
    { name: "Figma Blog", url: "https://www.figma.com/blog" },
    { name: "UX Collective", url: "https://uxdesign.cc" },
    { name: "Awwwards", url: "https://www.awwwards.com" },
    { name: "Dribbble Blog", url: "https://dribbble.com/stories" },
    { name: "Nielsen Norman Group", url: "https://www.nngroup.com/articles" },
    { name: "Sidebar", url: "https://sidebar.io" },
    { name: "Designmodo", url: "https://designmodo.com" },
    { name: "WebDesignerDepot", url: "https://www.webdesignerdepot.com" },
    { name: "InVision Blog", url: "https://www.invisionapp.com/inside-design" },
    { name: "UX Planet", url: "https://uxplanet.org" },
  
    // --- Tech Culture / General ---
    { name: "Motherboard (VICE)", url: "https://www.vice.com/en/topic/motherboard" },
    { name: "Mashable Tech", url: "https://mashable.com/tech" },
    { name: "Boing Boing", url: "https://boingboing.net" },
    { name: "The Atlantic Tech", url: "https://www.theatlantic.com/technology" },
    { name: "Salon Tech", url: "https://www.salon.com/technology" },
    { name: "Quartz Tech", url: "https://qz.com/technology" },
    { name: "Fast Company Tech", url: "https://www.fastcompany.com/tech" },
    { name: "Inc. Technology", url: "https://www.inc.com/technology" },
    { name: "Business Insider Tech", url: "https://www.businessinsider.com/tech" },
    { name: "MIT Sloan Review Tech", url: "https://sloanreview.mit.edu/tag/technology" },

      // --- Tech & Startups ---
  { name: "TechCrunch Startups", url: "https://techcrunch.com/startups" },
  { name: "VentureBeat Startups", url: "https://venturebeat.com/category/startups" },
  { name: "TNW Startups", url: "https://thenextweb.com/startups" },
  { name: "Crunchbase Startups", url: "https://news.crunchbase.com/startups" },
  { name: "Seedrs Blog", url: "https://www.seedrs.com/learn/blog" },
  { name: "AngelList Blog", url: "https://angel.co/blog" },
  { name: "Product Hunt Makers", url: "https://www.producthunt.com/topics/makers" },
  { name: "Indie Hackers Podcasts", url: "https://www.indiehackers.com/podcast" },
  { name: "SaaS Mag", url: "https://www.saasmag.com" },
  { name: "SaaStr Europa", url: "https://www.saastr.com/saastr-europa" },

  // --- AI & Machine Learning ---
  { name: "DeepLearning.ai", url: "https://www.deeplearning.ai/blog" },
  { name: "Fast.ai", url: "https://www.fast.ai/posts" },
  { name: "OpenAI Research", url: "https://openai.com/research" },
  { name: "Google Research Blog", url: "https://research.google/blog" },
  { name: "Microsoft Research Blog", url: "https://www.microsoft.com/en-us/research/blog" },
  { name: "Facebook AI Research", url: "https://research.facebook.com/blog" },
  { name: "NVIDIA AI", url: "https://blogs.nvidia.com/blog/category/ai" },
  { name: "Anthropic Research", url: "https://www.anthropic.com/research" },
  { name: "EleutherAI Research", url: "https://www.eleuther.ai" },
  { name: "MosaicML Research", url: "https://www.mosaicml.com/blog" },

  // --- Cybersecurity & Privacy ---
  { name: "Threatpost", url: "https://threatpost.com" },
  { name: "CyberScoop", url: "https://www.cyberscoop.com" },
  { name: "The Daily Swig", url: "https://portswigger.net/daily-swig" },
  { name: "BleepingComputer Security", url: "https://www.bleepingcomputer.com/news/security" },
  { name: "InfoSecurity Magazine", url: "https://www.infosecurity-magazine.com" },
  { name: "Security Boulevard", url: "https://securityboulevard.com" },
  { name: "Darktrace Blog", url: "https://www.darktrace.com/en/blog" },
  { name: "Palo Alto Networks Blog", url: "https://www.paloaltonetworks.com/blog" },
  { name: "Sophos News", url: "https://news.sophos.com" },
  { name: "CISA News", url: "https://www.cisa.gov/news-events" },

  // --- Cloud & Infrastructure ---
  { name: "AWS Compute Blog", url: "https://aws.amazon.com/blogs/compute" },
  { name: "AWS Machine Learning Blog", url: "https://aws.amazon.com/blogs/machine-learning" },
  { name: "Google Cloud Platform Blog", url: "https://cloud.google.com/blog/products/gcp" },
  { name: "Microsoft Azure Updates", url: "https://azure.microsoft.com/en-us/updates" },
  { name: "Oracle Cloud Updates", url: "https://blogs.oracle.com/cloud" },
  { name: "Cloudflare Updates", url: "https://blog.cloudflare.com" },
  { name: "DigitalOcean Updates", url: "https://www.digitalocean.com/blog" },
  { name: "Linode Blog", url: "https://www.linode.com/blog" },
  { name: "Heroku Blog", url: "https://blog.heroku.com" },
  { name: "Netlify Blog", url: "https://www.netlify.com/blog" },

  // --- Big Data & Analytics ---
  { name: "Databricks News", url: "https://databricks.com/blog" },
  { name: "Snowflake News", url: "https://www.snowflake.com/blog" },
  { name: "Cloudera Blog", url: "https://blog.cloudera.com" },
  { name: "Talend Blog", url: "https://www.talend.com/blog" },
  { name: "DataRobot Blog", url: "https://www.datarobot.com/blog" },
  { name: "Alteryx Blog", url: "https://www.alteryx.com/blog" },
  { name: "KDnuggets News", url: "https://www.kdnuggets.com" },
  { name: "Analytics Vidhya", url: "https://www.analyticsvidhya.com/blog" },
  { name: "Data Science Central", url: "https://www.datasciencecentral.com" },
  { name: "InsideBIGDATA", url: "https://insidebigdata.com" },

  // --- Crypto & Web3 ---
  { name: "Cointelegraph News", url: "https://cointelegraph.com/news" },
  { name: "Coindesk News", url: "https://www.coindesk.com/news" },
  { name: "Decrypt News", url: "https://decrypt.co/news" },
  { name: "The Block Crypto", url: "https://www.theblock.co/news" },
  { name: "Messari Blog", url: "https://messari.io/blog" },
  { name: "Bankless Media", url: "https://banklesshq.com/newsletter" },
  { name: "CryptoSlate News", url: "https://cryptoslate.com/news" },
  { name: "Bitcoin Magazine", url: "https://bitcoinmagazine.com/articles" },
  { name: "Ethereum Foundation Blog", url: "https://blog.ethereum.org" },
  { name: "Vitalik Buterin Blog", url: "https://vitalik.ca" },

  // --- Robotics / Future Tech ---
  { name: "IEEE Spectrum Robotics", url: "https://spectrum.ieee.org/robotics" },
  { name: "Robot Report", url: "https://www.therobotreport.com" },
  { name: "Robotics Business Review", url: "https://www.roboticsbusinessreview.com" },
  { name: "Boston Dynamics News", url: "https://www.bostondynamics.com/news" },
  { name: "Futurism Robotics", url: "https://futurism.com/tag/robotics" },
  { name: "Singularity Hub Robotics", url: "https://singularityhub.com/tag/robotics" },
  { name: "NextBigFuture Robotics", url: "https://www.nextbigfuture.com/tag/robotics" },
  { name: "Space.com Robotics", url: "https://www.space.com/topics/robotics" },
  { name: "NASA Robotics", url: "https://www.nasa.gov/topics/robotics" },
  { name: "European Space Agency Robotics", url: "https://www.esa.int/Robotics" },

  // --- Mobile & Consumer Electronics ---
  { name: "Android Central", url: "https://www.androidcentral.com" },
  { name: "iMore News", url: "https://www.imore.com/news" },
  { name: "Pocket-lint", url: "https://www.pocket-lint.com" },
  { name: "TechRadar Mobile", url: "https://www.techradar.com/news/phone-and-communications/mobile-phones" },
  { name: "TomsGuide Mobile", url: "https://www.tomsguide.com/news" },
  { name: "MacWorld Mobile", url: "https://www.macworld.com" },
  { name: "9to5Mac News", url: "https://9to5mac.com" },
  { name: "9to5Google News", url: "https://9to5google.com" },
  { name: "Gizmodo Mobile", url: "https://gizmodo.com/tag/mobile" },
  { name: "Engadget Mobile", url: "https://www.engadget.com/mobile" },

  // --- Gaming & Interactive Media ---
  { name: "Polygon Gaming", url: "https://www.polygon.com/gaming" },
  { name: "IGN Gaming", url: "https://www.ign.com/games" },
  { name: "GameSpot News", url: "https://www.gamespot.com/news" },
  { name: "Eurogamer News", url: "https://www.eurogamer.net/news" },
  { name: "Kotaku News", url: "https://kotaku.com" },
  { name: "PC Gamer", url: "https://www.pcgamer.com" },
  { name: "Rock Paper Shotgun", url: "https://www.rockpapershotgun.com" },
  { name: "Game Informer", url: "https://www.gameinformer.com" },
  { name: "Destructoid", url: "https://www.destructoid.com" },
  { name: "VG247", url: "https://www.vg247.com" },
  // --- Science & Research ---
  { name: "Scientific American", url: "https://www.scientificamerican.com" },
  { name: "Nature Technology", url: "https://www.nature.com/subjects/technology" },
  { name: "ScienceDaily Technology", url: "https://www.sciencedaily.com/news/computers_math/technology" },
  { name: "LiveScience Technology", url: "https://www.livescience.com/technology" },
  { name: "New Scientist Technology", url: "https://www.newscientist.com/section/technology" },
  { name: "Popular Science", url: "https://www.popsci.com" },
  { name: "Space.com Tech", url: "https://www.space.com/news" },
  { name: "NASA Tech", url: "https://www.nasa.gov/topics/technology" },
  { name: "ESA News Tech", url: "https://www.esa.int/Newsroom/Technology" },
  { name: "IEEE Spectrum Tech", url: "https://spectrum.ieee.org/technology" },

  // --- Business / Economy / Finance ---
  { name: "Business Insider Tech", url: "https://www.businessinsider.com/tech" },
  { name: "Fast Company Tech", url: "https://www.fastcompany.com/technology" },
  { name: "Inc. Tech", url: "https://www.inc.com/technology" },
  { name: "Harvard Business Review Tech", url: "https://hbr.org/topic/technology" },
  { name: "MIT Sloan Tech", url: "https://sloanreview.mit.edu/tag/technology" },
  { name: "Brookings Tech", url: "https://www.brookings.edu/topic/technology" },
  { name: "The Atlantic Tech", url: "https://www.theatlantic.com/technology" },
  { name: "The New Yorker Tech", url: "https://www.newyorker.com/news/tech" },
  { name: "Quartz Tech", url: "https://qz.com/technology" },
  { name: "The Drum Tech", url: "https://www.thedrum.com/technology" },

  // --- Design & UX / Product ---
  { name: "UX Collective", url: "https://uxdesign.cc" },
  { name: "UX Planet", url: "https://uxplanet.org" },
  { name: "Smashing Magazine", url: "https://www.smashingmagazine.com" },
  { name: "InVision Blog", url: "https://www.invisionapp.com/inside-design" },
  { name: "Awwwards", url: "https://www.awwwards.com" },
  { name: "Dribbble Blog", url: "https://dribbble.com/stories" },
  { name: "Nielsen Norman Group", url: "https://www.nngroup.com/articles" },
  { name: "Designmodo", url: "https://designmodo.com" },
  { name: "WebDesignerDepot", url: "https://www.webdesignerdepot.com" },
  { name: "Sidebar", url: "https://sidebar.io" },

  // --- Tech Culture & Media ---
  { name: "Boing Boing", url: "https://boingboing.net" },
  { name: "Motherboard (VICE)", url: "https://www.vice.com/en/topic/motherboard" },
  { name: "Mashable Tech", url: "https://mashable.com/tech" },
  { name: "Salon Tech", url: "https://www.salon.com/technology" },
  { name: "Wired Culture", url: "https://www.wired.com/category/culture" },
  { name: "Ars Technica Culture", url: "https://arstechnica.com/culture" },
  { name: "Engadget Culture", url: "https://www.engadget.com/culture" },
  { name: "The Verge Culture", url: "https://www.theverge.com/culture" },
  { name: "Fast Company Culture", url: "https://www.fastcompany.com/culture" },
  { name: "TechRadar Culture", url: "https://www.techradar.com/culture" }


  
  ];
  